library(cluster)
data("iris")
plot(iris$Sepal.Length,iris$Sepal.Width,main="Sepal Length vs Sepal Width",xlab="Sepal Length",ylab="Sepal Width")
x1=iris[,-5]
set.seed(240)
result=kmeans(x1,centers=3,nstart=20)
print(result)
cm=table(iris$Species,result$cluster)
print(cm)
plot(x1$Sepal.Length,x1$Sepal.Width,main="Sepal Length vs Sepal Width",xlab="Sepal Length",ylab="Sepal width",col=result$cluster)
points(result$centers,col=1:3,pch=8,cex=2)