setwd("C:/Users/Acer/Documents/Ram/ramy")
df=read.csv("h1.csv",header=TRUE)
print(df)
lr=lm(Height~Weight,data=df)
print(lr)
plot(df$Height,df$Weight,col="blue",main="Height-Weight Regression",cex=1.3,pch=15,xlab="Height",ylab="Weight")
print(summary(lr))
print(residuals(lr))
coeff=coefficients(lr)
eq=paste0("y=",round(coeff[2],1),"*x")
print(eq)
new.Weights=data.frame(Weight=c(60,50))
print(new.Weights)
df1=predict(lr,newdata=new.Weights)
print(df1)
df2=data.frame(df1,new.Weights)
names(df2)=c("Height","Weight")
print(df2)
df3=rbind(df,df2)
print(df3)
write.csv(df3,"h3.csv")
plot(df3$Height,df3$Weight,col="blue",main="Height-Weight Regression",cex=1.3,pch=15,xlab="Height",ylab="Weight")
pie(table(df3$Height))